In [1]:
# https://www.kaggle.com/datasets/blastchar/telco-customer-churn

In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [5]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [6]:
df.shape

(7043, 21)

In [7]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
df.shape

(7043, 21)

In [10]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [11]:
def object_to_int(dataframe_series):
    if dataframe_series.dtype=='object':
        dataframe_series = LabelEncoder().fit_transform(dataframe_series)
    return dataframe_series

In [12]:


df = df.apply(lambda x: object_to_int(x))
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,5375,0,0,1,0,1,0,1,0,0,...,0,0,0,0,0,1,2,29.85,2505,0
1,3962,1,0,0,0,34,1,0,0,2,...,2,0,0,0,1,0,3,56.95,1466,0
2,2564,1,0,0,0,2,1,0,0,2,...,0,0,0,0,0,1,3,53.85,157,1
3,5535,1,0,0,0,45,0,1,0,2,...,2,2,0,0,1,0,0,42.30,1400,0
4,6511,0,0,0,0,2,1,0,1,0,...,0,0,0,0,0,1,2,70.70,925,1

In [13]:
df = df.drop(['customerID'], axis = 1)

In [14]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,2505,0
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1466,0
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,157,1
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1400,0
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,925,1

In [15]:


X = df.drop(columns = ['Churn'])
y = df['Churn'].values

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.30, random_state = 1, stratify=y)

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
model_rf = RandomForestClassifier(n_estimators=1000 , n_jobs = -1,)
model_rf.fit(X_train, y_train)

rfprediction_test = model_rf.predict(X_test)

In [19]:
from sklearn.metrics import recall_score, confusion_matrix, precision_score, f1_score, accuracy_score, classification_report

In [20]:
print(classification_report(y_test, rfprediction_test))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87      1552
           1       0.65      0.48      0.56       561

    accuracy                           0.80      2113
   macro avg       0.74      0.70      0.71      2113
weighted avg       0.78      0.80      0.78      2113

In [21]:
print(accuracy_score(y_test, rfprediction_test))

0.7950780880265026

In [22]:
from sklearn.neighbors import KNeighborsClassifier

In [23]:
knn_model = KNeighborsClassifier(n_neighbors = 11) 
knn_model.fit(X_train,y_train)
predicted_y = knn_model.predict(X_test)
accuracy_knn = knn_model.score(X_test, y_test)

In [24]:
print(classification_report(y_test, predicted_y))
print(accuracy_score(y_test, predicted_y))

              precision    recall  f1-score   support

           0       0.80      0.91      0.85      1552
           1       0.60      0.35      0.44       561

    accuracy                           0.77      2113
   macro avg       0.70      0.63      0.65      2113
weighted avg       0.74      0.77      0.74      2113

0.7652626597255088

In [25]:
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression(max_iter=2000)
lr_model.fit(X_train , y_train)

LogisticRegression(max_iter=2000)

In [26]:
lr_pred= lr_model.predict(X_test)
print(classification_report(y_test, lr_pred))
print(accuracy_score(y_test, lr_pred))

              precision    recall  f1-score   support

           0       0.85      0.90      0.88      1552
           1       0.68      0.55      0.61       561

    accuracy                           0.81      2113
   macro avg       0.76      0.73      0.74      2113
weighted avg       0.80      0.81      0.80      2113

0.8111689540937056

In [27]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
dtmodel = DecisionTreeClassifier()
dtmodel.fit(X_train,y_train)
predictdt_y = dtmodel.predict(X_test)
accuracy_dt = dtmodel.score(X_test, y_test)

In [29]:
print(classification_report(y_test, predictdt_y))
print(accuracy_score(y_test, predictdt_y))

              precision    recall  f1-score   support

           0       0.82      0.81      0.81      1552
           1       0.49      0.50      0.49       561

    accuracy                           0.73      2113
   macro avg       0.65      0.65      0.65      2113
weighted avg       0.73      0.73      0.73      2113

0.7264552768575485

In [ ]:
import tensorflow as tf
nn = tf.keras.models.Sequential()
nn.add(tf.keras.layers.Dense(units=19, activation='relu'))

nn.add(tf.keras.layers.Dense(units=19, activation='relu'))
# nn.add(tf.keras.layers.Dropout(0.1))
nn.add(tf.keras.layers.Dense(units=15, activation='relu'))

nn.add(tf.keras.layers.Dense(units=10, activation='relu'))
# nn.add(tf.keras.layers.Dropout(0.1))
nn.add(tf.keras.layers.Dense(units=8, activation='relu'))

# nn.add(tf.keras.layers.Dense(units=1, activation='tanh')) #Output Layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

nn.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
history=nn.fit(X_train, y_train, batch_size = 16, epochs = 100, validation_split = 0.1)

Epoch 1/100

In [ ]:
from tensorflow.keras.utils import plot_model
plot_model(nn, show_shapes = True)

In [ ]:
nnypred=nn.predict(X_test)

In [ ]:
nnypred2 = [1 if x > 0.5 else 0 for x in nnypred ]

In [ ]:
print(classification_report(y_test, nnypred2))
print(accuracy_score(y_test, nnypred2))

In [ ]:
def model_performance_graphs2():
    
    fig, axes = plt.subplots(1, 2, figsize = (15, 8))

    axes[0].plot(history.epoch, history.history['accuracy'], label = 'acc')
    axes[0].plot(history.epoch, history.history['val_accuracy'], label = 'val_acc')
    axes[0].set_title('Accuracy vs Epochs', fontsize = 20)
    axes[0].set_xlabel('Epochs', fontsize = 15)
    axes[0].set_ylabel('Accuracy', fontsize = 15)
    axes[0].legend()

    axes[1].plot(history.epoch, history.history['loss'], label = 'loss')
    axes[1].plot(history.epoch, history.history['val_loss'], label="val_loss")
    axes[1].set_title("Loss Curve",fontsize=18)
    axes[1].set_xlabel("Epochs",fontsize=15)
    axes[1].set_ylabel("Loss",fontsize=15)
    axes[1].legend()

    plt.show()
    
model_performance_graphs2()